version: '3'
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel-app
        # restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./src:/var/www/laravel
        networks:
            - app-network
    web:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/var/www/laravel
        # restart: always
        networks:
            - app-network
    php:
        build:
            context: .
            dockerfile: ./docker/php/PHP.Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./src:/var/www/laravel
        # restart: always
        networks:
            - app-network
    
    #Node Service
    node:
        image: node:alpine
        container_name: laravel-node
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www/laravel
        networks:
            - app-network

    #Mysql Service
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'laravel_db'
        volumes:
            - laraveldata:/var/lib/mysql
        ports:
            - 3306:3306
        # restart: always
        networks:
            - app-network
volumes:
    laraveldata:
    
networks:
    app-network:
        driver: bridge